[
  {
    firstName: 'William',
    lastName: 'Green',
    userName: 'will-green',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Emma',
    lastName: 'Jones',
    userName: 'EmmaJ',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firsName: 'Christopher',
    lastName: 'Taylor',
    userName: '99Taylor',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firsName: 'Daniel',
    lastName: 'Moore',
    userName: 'danMoore',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firsName: 'Paul',
    lastName: 'Anderson',
    userName: 'p-And1001',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firsName: 'Mark',
    lastName: 'Thomas',
    userName: 'markcthomas',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Michael',
    lastName: 'Brown',
    userName: 'mikeyy',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    userName: 'emDav32',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Jacob',
    lastName: 'Miller',
    userName: 'JacobiM',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Madison',
    lastName: 'Wilson',
    userName: 'mads',
    password: '1',
    nativeLanguage: 'en',
    learnLanguage: 'es',
  },
  {
    firstName: 'Juan',
    lastName: 'Garcia',
    userName: 'jgarc11',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Maria',
    lastName: 'Rodriguez',
    userName: 'Mrod',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Diego',
    lastName: 'Martinez',
    userName: 'dmartinez',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Isabella',
    lastName: 'Perez',
    userName: 'isaperez',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Sofia',
    lastName: 'Gonzalez',
    userName: 'Sofia_G',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Lucas',
    lastName: 'Rodriguez',
    userName: 'Luca98',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Mateo',
    lastName: 'Garcia',
    userName: 'mgarcia1',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Alicia',
    lastName: 'Martinez',
    userName: 'amartinez1',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Adriana',
    lastName: 'Lopez',
    userName: 'alopez1',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Sebastian',
    lastName: 'Gonzalez',
    userName: 'sgonzalez2',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Valeria',
    lastName: 'Perez',
    userName: 'valP',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Leonardo',
    lastName: 'Sanchez',
    userName: 'lsanch_29',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Ximena',
    lastName: 'Mendez',
    userName: 'xmendez1',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Jose',
    lastName: 'Garcia',
    userName: 'joseee',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
  {
    firstName: 'Paula',
    lastName: 'Fernandez',
    userName: 'Paula39',
    password: '1',
    nativeLanguage: 'es',
    learnLanguage: 'en',
  },
];
